/**
 * Travel phrase deck for the New York trip.
 *
 * Everything is bundled in the app (no network, no API key) so it works on the
 * plane and in the subway. Each phrase carries a katakana reading because the
 * point is to be able to *say* it at the counter, not to read it.
 */

export type Situation =
  | "airport"
  | "hotel"
  | "restaurant"
  | "transit"
  | "shopping"
  | "sightseeing"
  | "smalltalk"
  | "trouble";

export const SITUATIONS: { key: Situation; label: string; icon: string; blurb: string }[] = [
  { key: "airport", label: "空港・入国審査", icon: "🛫", blurb: "JFK到着からホテルへ向かうまで" },
  { key: "hotel", label: "ホテル", icon: "🏨", blurb: "チェックイン・リクエスト・トラブル" },
  { key: "restaurant", label: "レストラン・カフェ", icon: "🍽️", blurb: "入店から会計・チップまで" },
  { key: "transit", label: "地下鉄・タクシー", icon: "🚇", blurb: "行き先を伝える・道をたずねる" },
  { key: "shopping", label: "買い物", icon: "🛍️", blurb: "試着・サイズ・支払い" },
  { key: "sightseeing", label: "観光・チケット", icon: "🗽", blurb: "入場・写真・列に並ぶ" },
  { key: "smalltalk", label: "あいさつ・雑談", icon: "💬", blurb: "ひとこと返せると旅が変わる" },
  { key: "trouble", label: "困ったとき", icon: "🆘", blurb: "体調・紛失・道に迷ったとき" },
];

export const SITUATION_LABELS = Object.fromEntries(
  SITUATIONS.map((s) => [s.key, s.label]),
) as Record<Situation, string>;

export const SITUATION_ICONS = Object.fromEntries(
  SITUATIONS.map((s) => [s.key, s.icon]),
) as Record<Situation, string>;

export interface Phrase {
  /** Stable id — progress is keyed on this, so never renumber an existing one. */
  id: string;
  situation: Situation;
  /** What you want to say, in Japanese. */
  ja: string;
  /** What to actually say. */
  en: string;
  /** Katakana reading. Not phonetically perfect — close enough to be understood. */
  kana: string;
  /** When and how to use it, or the local custom behind it. */
  tip?: string;
  /** A reply you are likely to hear back, so it doesn't catch you off guard. */
  reply?: string;
  replyJa?: string;
}

export const PHRASES: Phrase[] = [
  // ---------------------------------------------------------------- airport
  {
    id: "air-01",
    situation: "airport",
    ja: "観光で来ました。",
    en: "I'm here for sightseeing.",
    kana: "アイム ヒア フォー サイトシーイング",
    tip: "入国審査で必ず聞かれる「What's the purpose of your visit?」への答え。これだけは即答できるように。",
    reply: "How long are you staying?",
    replyJa: "どのくらい滞在しますか?",
  },
  {
    id: "air-02",
    situation: "airport",
    ja: "妻と2人で来ました。",
    en: "I'm traveling with my wife.",
    kana: "アイム トラベリング ウィズ マイ ワイフ",
    tip: "2人一緒に審査を受けるときは「We're traveling together.(一緒です)」も便利。",
  },
  {
    id: "air-03",
    situation: "airport",
    ja: "6日間の滞在です。",
    en: "I'm staying for six days.",
    kana: "アイム ステイイング フォー シックス デイズ",
    tip: "日数を入れ替えるだけ。9/18〜9/23なら six days。",
  },
  {
    id: "air-04",
    situation: "airport",
    ja: "マンハッタンのホテルに泊まります。",
    en: "We're staying at a hotel in Manhattan.",
    kana: "ウィア ステイイング アット ア ホテル イン マンハッタン",
    tip: "滞在先を聞かれたら地区名まで言えば十分。住所を見せるのが一番早い。",
  },
  {
    id: "air-05",
    situation: "airport",
    ja: "これは友人へのお土産です。",
    en: "These are souvenirs for my friends.",
    kana: "ジーズ アー スーベニアズ フォー マイ フレンズ",
    tip: "荷物を開けられたときの説明に。食品は肉類がNGなので正直に申告を。",
  },
  {
    id: "air-06",
    situation: "airport",
    ja: "スーツケースが出てきません。",
    en: "My suitcase didn't come out.",
    kana: "マイ スーツケース ディドゥント カム アウト",
    tip: "バゲージクレームの係員へ。荷物のタグ(claim tag)を見せながら言うと早い。",
  },
  {
    id: "air-07",
    situation: "airport",
    ja: "タクシー乗り場はどこですか?",
    en: "Where is the taxi stand?",
    kana: "ウェア イズ ザ タクシー スタンド",
    tip: "JFKは正規の黄色いタクシー乗り場以外で声をかけてくる客引きに乗らないこと。",
  },
  {
    id: "air-08",
    situation: "airport",
    ja: "市内へはどう行けばいいですか?",
    en: "How do I get into the city?",
    kana: "ハウ ドゥ アイ ゲット イントゥ ザ シティ",
    tip: "ニューヨークで the city はマンハッタンを指すことが多い。",
  },
  {
    id: "air-09",
    situation: "airport",
    ja: "すみません、もう一度お願いします。",
    en: "Sorry, could you say that again?",
    kana: "ソーリー クッジュー セイ ザット アゲイン",
    tip: "聞き取れなかったら黙らずこれ。旅行中いちばん使う一文です。",
  },
  {
    id: "air-10",
    situation: "airport",
    ja: "もう少しゆっくり話してもらえますか?",
    en: "Could you speak a little more slowly?",
    kana: "クッジュー スピーク ア リトル モア スローリー",
    tip: "a little を入れるとやわらかい。早口のNYではこれが効きます。",
  },
  {
    id: "air-11",
    situation: "airport",
    ja: "Wi-Fiのパスワードを教えてください。",
    en: "Could I get the Wi-Fi password?",
    kana: "クダイ ゲット ザ ワイファイ パスワード",
    tip: "空港・カフェ・ホテルどこでも使える万能形「Could I get 〜?」。",
  },
  {
    id: "air-12",
    situation: "airport",
    ja: "現金をおろせる場所はありますか?",
    en: "Is there an ATM around here?",
    kana: "イズ ゼア アン エーティーエム アラウンド ヒア",
    tip: "チップ用に1ドル札を作っておくと安心。",
  },

  // ------------------------------------------------------------------ hotel
  {
    id: "hot-01",
    situation: "hotel",
    ja: "チェックインをお願いします。",
    en: "I'd like to check in, please.",
    kana: "アイド ライク トゥ チェック イン プリーズ",
    reply: "May I have your passport?",
    replyJa: "パスポートをお願いします。",
  },
  {
    id: "hot-02",
    situation: "hotel",
    ja: "田中で予約しています。",
    en: "I have a reservation under Tanaka.",
    kana: "アイ ハブ ア レザベーション アンダー タナカ",
    tip: "under 〜 で「〜の名前で」。予約名は聞き取りにくいのでスペルも言えると確実。",
  },
  {
    id: "hot-03",
    situation: "hotel",
    ja: "荷物を預かってもらえますか?",
    en: "Could you hold our bags, please?",
    kana: "クッジュー ホールド アワ バッグズ プリーズ",
    tip: "チェックイン前・チェックアウト後の定番。受け取りは引換札(ticket)で。",
  },
  {
    id: "hot-04",
    situation: "hotel",
    ja: "チェックアウトは何時ですか?",
    en: "What time is checkout?",
    kana: "ワッタイム イズ チェックアウト",
  },
  {
    id: "hot-05",
    situation: "hotel",
    ja: "部屋を変えてもらえますか?",
    en: "Could we change rooms?",
    kana: "クッド ウィ チェンジ ルームズ",
    tip: "理由も添えると通りやすい。「It's very noisy.(とてもうるさくて)」など。",
  },
  {
    id: "hot-06",
    situation: "hotel",
    ja: "お湯が出ません。",
    en: "There's no hot water.",
    kana: "ゼアズ ノー ホット ウォーター",
    tip: "不具合はぜんぶ「There's no 〜」「〜 isn't working」で言えます。",
  },
  {
    id: "hot-07",
    situation: "hotel",
    ja: "タオルをあと2枚もらえますか?",
    en: "Could we get two more towels?",
    kana: "クッド ウィ ゲット トゥー モア タオルズ",
    tip: "枕(pillows)、水(bottles of water)も同じ形で頼めます。",
  },
  {
    id: "hot-08",
    situation: "hotel",
    ja: "近くにおすすめのお店はありますか?",
    en: "Do you know a good place to eat nearby?",
    kana: "ドゥ ユー ノウ ア グッド プレイス トゥ イート ニアバイ",
    tip: "フロントのおすすめは当たりが多い。地図をもらって印をつけてもらおう。",
  },
  {
    id: "hot-09",
    situation: "hotel",
    ja: "タクシーを呼んでもらえますか?",
    en: "Could you call a taxi for us?",
    kana: "クッジュー コール ア タクシー フォー アス",
  },
  {
    id: "hot-10",
    situation: "hotel",
    ja: "朝食は何時からですか?",
    en: "What time does breakfast start?",
    kana: "ワッタイム ダズ ブレックファスト スタート",
  },
  {
    id: "hot-11",
    situation: "hotel",
    ja: "金庫の使い方を教えてください。",
    en: "Could you show me how to use the safe?",
    kana: "クッジュー ショウ ミー ハウ トゥ ユーズ ザ セイフ",
    tip: "「Could you show me how to 〜?」は使い方全般に効く便利な型。",
  },
  {
    id: "hot-12",
    situation: "hotel",
    ja: "もう1泊できますか?",
    en: "Is it possible to stay one more night?",
    kana: "イズ イット ポッシブル トゥ ステイ ワン モア ナイト",
  },

  // ------------------------------------------------------------- restaurant
  {
    id: "res-01",
    situation: "restaurant",
    ja: "2名です。",
    en: "Table for two, please.",
    kana: "テーブル フォー トゥー プリーズ",
    tip: "入口で待って案内されるのがNY流。空いてる席に勝手に座らない。",
    reply: "Do you have a reservation?",
    replyJa: "ご予約はありますか?",
  },
  {
    id: "res-02",
    situation: "restaurant",
    ja: "予約はしていません。",
    en: "We don't have a reservation.",
    kana: "ウィ ドント ハブ ア レザベーション",
  },
  {
    id: "res-03",
    situation: "restaurant",
    ja: "どのくらい待ちますか?",
    en: "How long is the wait?",
    kana: "ハウ ロング イズ ザ ウェイト",
    tip: "名前と電話番号を伝えると、順番が来たらSMSで呼んでくれる店も多い。",
  },
  {
    id: "res-04",
    situation: "restaurant",
    ja: "おすすめは何ですか?",
    en: "What do you recommend?",
    kana: "ワット ドゥ ユー レコメンド",
    tip: "迷ったらこれ。答えが聞き取れなくても「I'll have that.」でOK。",
  },
  {
    id: "res-05",
    situation: "restaurant",
    ja: "これは辛いですか?",
    en: "Is this spicy?",
    kana: "イズ ジス スパイシー",
  },
  {
    id: "res-06",
    situation: "restaurant",
    ja: "同じものをください。",
    en: "I'll have the same, please.",
    kana: "アイル ハブ ザ セイム プリーズ",
    tip: "妻が先に頼んだあとに使える省エネフレーズ。",
  },
  {
    id: "res-07",
    situation: "restaurant",
    ja: "取り分け用のお皿をもらえますか?",
    en: "Could we get an extra plate?",
    kana: "クッド ウィ ゲット アン エクストラ プレイト",
    tip: "2人でシェアするときに。量が多いNYでは必須。",
  },
  {
    id: "res-08",
    situation: "restaurant",
    ja: "お水をお願いします。",
    en: "Could we get some water, please?",
    kana: "クッド ウィ ゲット サム ウォーター プリーズ",
    tip: "無料の水が欲しいときは tap water。ただ water だと有料の瓶が来ることも。",
  },
  {
    id: "res-09",
    situation: "restaurant",
    ja: "持ち帰りにできますか?",
    en: "Could I get this to go?",
    kana: "クダイ ゲット ジス トゥ ゴー",
    tip: "食べ残しを包んでもらうのは普通のこと。「Can I get a box?」でも通じます。",
  },
  {
    id: "res-10",
    situation: "restaurant",
    ja: "お会計をお願いします。",
    en: "Could we get the check, please?",
    kana: "クッド ウィ ゲット ザ チェック プリーズ",
    tip: "アメリカでは bill でなく check。レジに行かず席で払うのが基本。",
  },
  {
    id: "res-11",
    situation: "restaurant",
    ja: "カードで払えますか?",
    en: "Can I pay by card?",
    kana: "キャナイ ペイ バイ カード",
  },
  {
    id: "res-12",
    situation: "restaurant",
    ja: "別々に払えますか?",
    en: "Could we pay separately?",
    kana: "クッド ウィ ペイ セパレットリー",
    tip: "「Can you split the check?」も同じ意味でよく使われます。",
  },
  {
    id: "res-13",
    situation: "restaurant",
    ja: "チップは込みですか?",
    en: "Is gratuity included?",
    kana: "イズ グラチュイティ インクルーデッド",
    tip: "NYはチップ18〜20%が目安。伝票に「gratuity included」とあれば追加不要。",
  },
  {
    id: "res-14",
    situation: "restaurant",
    ja: "とてもおいしかったです。",
    en: "That was delicious, thank you.",
    kana: "ザット ワズ デリシャス サンキュー",
    tip: "帰りぎわのひとこと。店員さんの反応が変わります。",
  },

  // ---------------------------------------------------------------- transit
  {
    id: "tra-01",
    situation: "transit",
    ja: "タイムズスクエアまでお願いします。",
    en: "Times Square, please.",
    kana: "タイムズ スクエア プリーズ",
    tip: "タクシーは行き先を短く言うだけで通じます。住所なら番地→通りの順。",
  },
  {
    id: "tra-02",
    situation: "transit",
    ja: "この角で降ろしてください。",
    en: "Could you drop us off at this corner?",
    kana: "クッジュー ドロップ アス オフ アット ジス コーナー",
    tip: "NYのタクシーは交差点単位で止まるのが普通。",
  },
  {
    id: "tra-03",
    situation: "transit",
    ja: "どのくらい時間がかかりますか?",
    en: "How long does it take?",
    kana: "ハウ ロング ダズ イット テイク",
  },
  {
    id: "tra-04",
    situation: "transit",
    ja: "この電車はブルックリンに行きますか?",
    en: "Does this train go to Brooklyn?",
    kana: "ダズ ジス トレイン ゴー トゥ ブルックリン",
    tip: "同じホームに急行(express)と各停(local)が来るので、乗る前にひと声かけると安全。",
  },
  {
    id: "tra-05",
    situation: "transit",
    ja: "どこで乗り換えますか?",
    en: "Where do I transfer?",
    kana: "ウェア ドゥ アイ トランスファー",
  },
  {
    id: "tra-06",
    situation: "transit",
    ja: "ここは何駅ですか?",
    en: "What stop is this?",
    kana: "ワット ストップ イズ ジス",
    tip: "地下鉄のアナウンスは聞き取りにくいので、隣の人にこれを。",
  },
  {
    id: "tra-07",
    situation: "transit",
    ja: "アップタウン方面のホームはどこですか?",
    en: "Where's the uptown platform?",
    kana: "ウェアズ ジ アップタウン プラットフォーム",
    tip: "NYの地下鉄は北行き=uptown、南行き=downtown。改札を入る前に確認を(入り直すと再課金)。",
  },
  {
    id: "tra-08",
    situation: "transit",
    ja: "ここは歩いてどのくらいですか?",
    en: "How far is it on foot?",
    kana: "ハウ ファー イズ イット オン フット",
    tip: "マンハッタンは20ブロックで約1.6km、徒歩20分が目安。",
  },
  {
    id: "tra-09",
    situation: "transit",
    ja: "道に迷ってしまいました。",
    en: "I think we're lost.",
    kana: "アイ シンク ウィア ロスト",
  },
  {
    id: "tra-10",
    situation: "transit",
    ja: "ここへの行き方を教えてもらえますか?",
    en: "Could you show me how to get here?",
    kana: "クッジュー ショウ ミー ハウ トゥ ゲット ヒア",
    tip: "スマホの地図を見せながら言うのが最強。指をさすだけで伝わります。",
  },
  {
    id: "tra-11",
    situation: "transit",
    ja: "すみません、降ります。",
    en: "Excuse me, this is my stop.",
    kana: "エクスキューズ ミー ジス イズ マイ ストップ",
    tip: "混んだ車内ではこれを言いながら進めば道をあけてくれます。",
  },
  {
    id: "tra-12",
    situation: "transit",
    ja: "改札はどこですか?",
    en: "Where can I tap in?",
    kana: "ウェア キャナイ タップ イン",
    tip: "今のNY地下鉄はOMNYで、クレジットカードやiPhoneをそのままタッチして乗れます。",
  },

  // --------------------------------------------------------------- shopping
  {
    id: "sho-01",
    situation: "shopping",
    ja: "見ているだけです。",
    en: "I'm just looking, thanks.",
    kana: "アイム ジャスト ルッキング サンクス",
    tip: "「Can I help you?」と声をかけられたときの定番の返し。無視せずこれを。",
  },
  {
    id: "sho-02",
    situation: "shopping",
    ja: "試着してもいいですか?",
    en: "Can I try this on?",
    kana: "キャナイ トライ ジス オン",
  },
  {
    id: "sho-03",
    situation: "shopping",
    ja: "もう少し大きいサイズはありますか?",
    en: "Do you have this in a bigger size?",
    kana: "ドゥ ユー ハブ ジス イン ア ビガー サイズ",
    tip: "色違いなら in another color。同じ型で聞けます。",
  },
  {
    id: "sho-04",
    situation: "shopping",
    ja: "他の色はありますか?",
    en: "Do you have this in another color?",
    kana: "ドゥ ユー ハブ ジス イン アナザー カラー",
  },
  {
    id: "sho-05",
    situation: "shopping",
    ja: "これはいくらですか?",
    en: "How much is this?",
    kana: "ハウ マッチ イズ ジス",
  },
  {
    id: "sho-06",
    situation: "shopping",
    ja: "これは税込みの値段ですか?",
    en: "Does that include tax?",
    kana: "ダズ ザット インクルード タックス",
    tip: "NY市の売上税は約8.875%。値札は税別なので、レジで少し高くなります。",
  },
  {
    id: "sho-07",
    situation: "shopping",
    ja: "これをください。",
    en: "I'll take this one.",
    kana: "アイル テイク ジス ワン",
  },
  {
    id: "sho-08",
    situation: "shopping",
    ja: "別々に包んでもらえますか?",
    en: "Could you wrap them separately?",
    kana: "クッジュー ラップ ゼム セパレットリー",
    tip: "お土産を配るときに便利。",
  },
  {
    id: "sho-09",
    situation: "shopping",
    ja: "袋をもらえますか?",
    en: "Could I get a bag?",
    kana: "クダイ ゲット ア バッグ",
    tip: "NYはレジ袋が有料または廃止。エコバッグを持っていくと安心です。",
  },
  {
    id: "sho-10",
    situation: "shopping",
    ja: "サイズが合わなければ返品できますか?",
    en: "Can I return this if it doesn't fit?",
    kana: "キャナイ リターン ジス イフ イット ダズント フィット",
    tip: "返品にはレシートが必要。旅行中は期限も確認しておくと安心。",
  },
  {
    id: "sho-11",
    situation: "shopping",
    ja: "レシートをください。",
    en: "Could I have the receipt?",
    kana: "クダイ ハブ ザ レシート",
  },
  {
    id: "sho-12",
    situation: "shopping",
    ja: "少し考えます。",
    en: "I'll think about it, thanks.",
    kana: "アイル シンク アバウト イット サンクス",
    tip: "断りたいときの角が立たない言い方。",
  },

  // ------------------------------------------------------------ sightseeing
  {
    id: "sig-01",
    situation: "sightseeing",
    ja: "大人2枚お願いします。",
    en: "Two adults, please.",
    kana: "トゥー アダルツ プリーズ",
  },
  {
    id: "sig-02",
    situation: "sightseeing",
    ja: "当日券はありますか?",
    en: "Do you have any tickets for today?",
    kana: "ドゥ ユー ハブ エニー チケッツ フォー トゥデイ",
    tip: "ミュージカルの当日券はTKTS(タイムズスクエア)で割引があります。",
  },
  {
    id: "sig-03",
    situation: "sightseeing",
    ja: "何時まで開いていますか?",
    en: "What time do you close?",
    kana: "ワッタイム ドゥ ユー クローズ",
  },
  {
    id: "sig-04",
    situation: "sightseeing",
    ja: "写真を撮ってもらえますか?",
    en: "Could you take a picture of us?",
    kana: "クッジュー テイク ア ピクチャー オブ アス",
    tip: "夫婦の写真を残す最重要フレーズ。スマホを渡しながら言えば確実。",
  },
  {
    id: "sig-05",
    situation: "sightseeing",
    ja: "もう1枚お願いします。",
    en: "Could you take one more?",
    kana: "クッジュー テイク ワン モア",
  },
  {
    id: "sig-06",
    situation: "sightseeing",
    ja: "ここで写真を撮ってもいいですか?",
    en: "Is it OK to take pictures here?",
    kana: "イズ イット オーケー トゥ テイク ピクチャーズ ヒア",
    tip: "美術館は作品ごとに撮影不可のことがあります。ひと言聞けば安心。",
  },
  {
    id: "sig-07",
    situation: "sightseeing",
    ja: "荷物を預ける場所はありますか?",
    en: "Is there a place to check our bags?",
    kana: "イズ ゼア ア プレイス トゥ チェック アワ バッグズ",
    tip: "大きなリュックは持ち込めない美術館が多く、クロークに預けます。",
  },
  {
    id: "sig-08",
    situation: "sightseeing",
    ja: "日本語のパンフレットはありますか?",
    en: "Do you have a brochure in Japanese?",
    kana: "ドゥ ユー ハブ ア ブロシュア イン ジャパニーズ",
    tip: "MoMAやメトロポリタン美術館は日本語のガイドがあります。",
  },
  {
    id: "sig-09",
    situation: "sightseeing",
    ja: "この列はどのくらい待ちますか?",
    en: "How long is this line?",
    kana: "ハウ ロング イズ ジス ライン",
    tip: "アメリカでは行列は queue でなく line。「並んでいますか?」は「Are you in line?」。",
  },
  {
    id: "sig-10",
    situation: "sightseeing",
    ja: "お手洗いはどこですか?",
    en: "Where's the restroom?",
    kana: "ウェアズ ザ レストルーム",
    tip: "toilet より restroom / bathroom が自然です。",
  },
  {
    id: "sig-11",
    situation: "sightseeing",
    ja: "展望台へはどう行きますか?",
    en: "How do we get to the observation deck?",
    kana: "ハウ ドゥ ウィ ゲット トゥ ジ オブザベーション デック",
  },
  {
    id: "sig-12",
    situation: "sightseeing",
    ja: "チケット売り場はどこですか?",
    en: "Where's the box office?",
    kana: "ウェアズ ザ ボックス オフィス",
    tip: "劇場・スタジアムのチケット窓口は box office。",
  },

  // -------------------------------------------------------------- smalltalk
  {
    id: "sma-01",
    situation: "smalltalk",
    ja: "元気です、ありがとう。そちらは?",
    en: "Good, thanks. How are you?",
    kana: "グッド サンクス ハウ アー ユー",
    tip: "店員の「How are you doing?」は挨拶。中身より返すことが大事。",
  },
  {
    id: "sma-02",
    situation: "smalltalk",
    ja: "日本から来ました。",
    en: "We're from Japan.",
    kana: "ウィア フロム ジャパン",
  },
  {
    id: "sma-03",
    situation: "smalltalk",
    ja: "ニューヨークは初めてです。",
    en: "This is our first time in New York.",
    kana: "ジス イズ アワ ファースト タイム イン ニューヨーク",
    tip: "これを言うとおすすめを教えてくれることが多い、会話が広がる一言。",
  },
  {
    id: "sma-04",
    situation: "smalltalk",
    ja: "妻です。",
    en: "This is my wife.",
    kana: "ジス イズ マイ ワイフ",
  },
  {
    id: "sma-05",
    situation: "smalltalk",
    ja: "結婚記念日の旅行なんです。",
    en: "We're here for our anniversary.",
    kana: "ウィア ヒア フォー アワ アニバーサリー",
    tip: "レストランで言うとデザートをサービスしてくれることも。",
  },
  {
    id: "sma-06",
    situation: "smalltalk",
    ja: "英語は少しだけ話せます。",
    en: "I speak a little English.",
    kana: "アイ スピーク ア リトル イングリッシュ",
    tip: "先に言っておくと、相手がゆっくり話してくれます。",
  },
  {
    id: "sma-07",
    situation: "smalltalk",
    ja: "ありがとう、助かりました。",
    en: "Thank you, you've been a big help.",
    kana: "サンキュー ユーブ ビーン ア ビッグ ヘルプ",
  },
  {
    id: "sma-08",
    situation: "smalltalk",
    ja: "お先にどうぞ。",
    en: "After you.",
    kana: "アフター ユー",
    tip: "ドアやエレベーターで。短いのに好印象な一言。",
  },
  {
    id: "sma-09",
    situation: "smalltalk",
    ja: "すみません(通してください)。",
    en: "Excuse me.",
    kana: "エクスキューズ ミー",
    tip: "人に話しかけるとき・前を通るとき両方に使えます。",
  },
  {
    id: "sma-10",
    situation: "smalltalk",
    ja: "それ、すごくいいですね!",
    en: "That sounds great!",
    kana: "ザット サウンズ グレイト",
  },
  {
    id: "sma-11",
    situation: "smalltalk",
    ja: "よい一日を!",
    en: "Have a good one!",
    kana: "ハブ ア グッド ワン",
    tip: "店を出るときの決まり文句。NYらしい軽い挨拶です。",
  },
  {
    id: "sma-12",
    situation: "smalltalk",
    ja: "また来ますね。",
    en: "We'll be back!",
    kana: "ウィル ビー バック",
  },

  // ---------------------------------------------------------------- trouble
  {
    id: "trb-01",
    situation: "trouble",
    ja: "助けてもらえますか?",
    en: "Could you help me?",
    kana: "クッジュー ヘルプ ミー",
  },
  {
    id: "trb-02",
    situation: "trouble",
    ja: "財布をなくしました。",
    en: "I lost my wallet.",
    kana: "アイ ロスト マイ ウォレット",
    tip: "パスポートなら my passport。落とし物は lost and found へ。",
  },
  {
    id: "trb-03",
    situation: "trouble",
    ja: "警察を呼んでください。",
    en: "Please call the police.",
    kana: "プリーズ コール ザ ポリス",
    tip: "緊急時は911。警察・救急・消防すべてこの番号です。",
  },
  {
    id: "trb-04",
    situation: "trouble",
    ja: "気分が悪いです。",
    en: "I'm not feeling well.",
    kana: "アイム ノット フィーリング ウェル",
  },
  {
    id: "trb-05",
    situation: "trouble",
    ja: "近くに薬局はありますか?",
    en: "Is there a pharmacy nearby?",
    kana: "イズ ゼア ア ファーマシー ニアバイ",
    tip: "NYではDuane ReadeやCVSが街のいたるところにあります。",
  },
  {
    id: "trb-06",
    situation: "trouble",
    ja: "病院に行きたいのですが。",
    en: "I need to get to a hospital.",
    kana: "アイ ニード トゥ ゲット トゥ ア ホスピタル",
    tip: "海外旅行保険の連絡先をスマホに控えておきましょう。",
  },
  {
    id: "trb-07",
    situation: "trouble",
    ja: "日本語を話せる人はいますか?",
    en: "Is there anyone who speaks Japanese?",
    kana: "イズ ゼア エニワン フー スピークス ジャパニーズ",
  },
  {
    id: "trb-08",
    situation: "trouble",
    ja: "スマホを盗まれました。",
    en: "My phone was stolen.",
    kana: "マイ フォン ワズ ストールン",
  },
  {
    id: "trb-09",
    situation: "trouble",
    ja: "妻とはぐれてしまいました。",
    en: "I got separated from my wife.",
    kana: "アイ ガット セパレイテッド フロム マイ ワイフ",
    tip: "はぐれたときの集合場所を先に決めておくと安心です。",
  },
  {
    id: "trb-10",
    situation: "trouble",
    ja: "えびのアレルギーがあります。",
    en: "I'm allergic to shrimp.",
    kana: "アイム アラジック トゥ シュリンプ",
    tip: "アレルギーは命に関わるので、注文前にはっきり伝えましょう。",
  },
  {
    id: "trb-11",
    situation: "trouble",
    ja: "どこかで充電できますか?",
    en: "Is there somewhere I can charge my phone?",
    kana: "イズ ゼア サムウェア アイ キャン チャージ マイ フォン",
  },
  {
    id: "trb-12",
    situation: "trouble",
    ja: "けっこうです。",
    en: "No, thank you. I'm fine.",
    kana: "ノー サンキュー アイム ファイン",
    tip: "タイムズスクエアの着ぐるみやCD配りは有料。はっきり断って歩き続けるのが安全です。",
  },
];

export const PHRASE_BY_ID: Record<string, Phrase> = Object.fromEntries(
  PHRASES.map((p) => [p.id, p]),
);

export function phrasesOf(situation: Situation): Phrase[] {
  return PHRASES.filter((p) => p.situation === situation);
}
