/**
 * Travel vocabulary deck for the New York trip: the single words and the
 * idioms/phrasal verbs you actually hear at a JFK counter, on the subway and
 * at a diner.
 *
 * Everything is bundled in the app (no network, no API key), so it works
 * offline on the plane and in the subway.
 * Every entry carries a katakana reading and a real example sentence: knowing
 * "entrée" is useless unless you recognise it when the server says it.
 */

export type WordGroup =
  | "airport"
  | "transit"
  | "hotel"
  | "food"
  | "shopping"
  | "money"
  | "sightseeing"
  | "street"
  | "smalltalk"
  | "trouble";

/** 単語 か 熟語(句動詞・決まり文句)か。学習の絞り込みに使います。 */
export type WordType = "word" | "idiom";

export const WORD_GROUPS: { key: WordGroup; label: string; icon: string; blurb: string }[] = [
  { key: "airport", label: "空港・機内", icon: "🛫", blurb: "搭乗から入国審査・預け荷物まで" },
  { key: "transit", label: "地下鉄・移動", icon: "🚇", blurb: "uptown / express など乗りこなす語" },
  { key: "hotel", label: "ホテル", icon: "🏨", blurb: "チェックインと客室まわり" },
  { key: "food", label: "食事・カフェ", icon: "🍽️", blurb: "注文・会計・チップの必須語" },
  { key: "shopping", label: "買い物", icon: "🛍️", blurb: "試着・返品・セールの言い方" },
  { key: "money", label: "お金・チップ", icon: "💵", blurb: "支払いで戸惑わないために" },
  { key: "sightseeing", label: "観光・チケット", icon: "🗽", blurb: "入場・予約・展示の英語" },
  { key: "street", label: "街の表示・看板", icon: "🚧", blurb: "読めないと困る掲示の英語" },
  { key: "smalltalk", label: "あいさつ・雑談", icon: "💬", blurb: "ニューヨーカーの口ぐせ" },
  { key: "trouble", label: "困ったとき", icon: "🆘", blurb: "体調・紛失・トラブルの語彙" },
];

export const GROUP_LABELS = Object.fromEntries(
  WORD_GROUPS.map((g) => [g.key, g.label]),
) as Record<WordGroup, string>;

export const GROUP_ICONS = Object.fromEntries(
  WORD_GROUPS.map((g) => [g.key, g.icon]),
) as Record<WordGroup, string>;

export interface WordEntry {
  /** Stable id — progress is keyed on this, so never renumber an existing one. */
  id: string;
  group: WordGroup;
  type: WordType;
  /** The word or idiom itself. */
  en: string;
  /** Katakana reading. Not phonetically perfect — close enough to be understood. */
  kana: string;
  /** Japanese meaning. */
  ja: string;
  /** 品詞や使い方の区分(名詞・動詞・熟語 など)。 */
  pos: string;
  /** A sentence you could really hear or say in New York. */
  example: string;
  exampleJa: string;
  /** Where it trips Japanese travellers up, or the local custom behind it. */
  note?: string;
}

export const WORDS: WordEntry[] = [
  // --------------------------------------------------------------- airport
  {
    id: "vc-air-01",
    group: "airport",
    type: "word",
    en: "immigration",
    kana: "イミグレーション",
    ja: "入国審査",
    pos: "名詞",
    example: "Follow the signs to immigration.",
    exampleJa: "案内表示に従って入国審査へ進んでください。",
    note: "審査官のブースは passport control とも書かれます。",
  },
  {
    id: "vc-air-02",
    group: "airport",
    type: "word",
    en: "customs",
    kana: "カスタムズ",
    ja: "税関",
    pos: "名詞",
    example: "You'll go through customs after you pick up your bags.",
    exampleJa: "荷物を受け取ったあとに税関を通ります。",
    note: "いつも複数形。costume(衣装)と混同しないように。",
  },
  {
    id: "vc-air-03",
    group: "airport",
    type: "word",
    en: "baggage claim",
    kana: "バゲージ クレイム",
    ja: "手荷物受取所",
    pos: "名詞",
    example: "Baggage claim is one floor down.",
    exampleJa: "手荷物受取所は1つ下の階です。",
    note: "claim は「苦情」ではなく「受け取り」。日本語のクレームとは意味が違います。",
  },
  {
    id: "vc-air-04",
    group: "airport",
    type: "word",
    en: "carry-on",
    kana: "キャリーオン",
    ja: "機内持ち込み手荷物",
    pos: "名詞",
    example: "Is this your only carry-on?",
    exampleJa: "機内持ち込みはこれだけですか?",
  },
  {
    id: "vc-air-05",
    group: "airport",
    type: "word",
    en: "layover",
    kana: "レイオーバー",
    ja: "乗り継ぎ(の待ち時間)",
    pos: "名詞",
    example: "We have a three-hour layover in Dallas.",
    exampleJa: "ダラスで3時間の乗り継ぎがあります。",
  },
  {
    id: "vc-air-06",
    group: "airport",
    type: "word",
    en: "aisle seat",
    kana: "アイル スィート",
    ja: "通路側の席",
    pos: "名詞",
    example: "Could I have an aisle seat, please?",
    exampleJa: "通路側の席にしてもらえますか?",
    note: "aisle の s は発音しません。窓側は window seat。",
  },
  {
    id: "vc-air-07",
    group: "airport",
    type: "word",
    en: "overhead bin",
    kana: "オーバーヘッド ビン",
    ja: "頭上の荷物棚",
    pos: "名詞",
    example: "Please place your bag in the overhead bin.",
    exampleJa: "かばんは頭上の棚に入れてください。",
  },
  {
    id: "vc-air-08",
    group: "airport",
    type: "word",
    en: "delayed",
    kana: "ディレイド",
    ja: "遅れている",
    pos: "形容詞",
    example: "Our flight is delayed by two hours.",
    exampleJa: "私たちの便は2時間遅れています。",
    note: "空港の掲示板では on time(定刻)/ delayed / canceled の3つを見ます。",
  },
  {
    id: "vc-air-09",
    group: "airport",
    type: "word",
    en: "declare",
    kana: "ディクレア",
    ja: "(税関で)申告する",
    pos: "動詞",
    example: "Do you have anything to declare?",
    exampleJa: "申告するものはありますか?",
    note: "食品や現金1万ドル超は申告が必要。答えは Nothing to declare. が定番。",
  },
  {
    id: "vc-air-10",
    group: "airport",
    type: "idiom",
    en: "check in",
    kana: "チェック イン",
    ja: "搭乗手続きをする",
    pos: "熟語",
    example: "You can check in online 24 hours before the flight.",
    exampleJa: "出発24時間前からオンラインで搭乗手続きができます。",
    note: "ホテルの「チェックイン」と同じ形。名詞は check-in とハイフンつき。",
  },
  {
    id: "vc-air-11",
    group: "airport",
    type: "idiom",
    en: "fill out",
    kana: "フィル アウト",
    ja: "(書類に)記入する",
    pos: "熟語",
    example: "Please fill out this form before you get in line.",
    exampleJa: "列に並ぶ前にこの用紙に記入してください。",
  },
  {
    id: "vc-air-12",
    group: "airport",
    type: "idiom",
    en: "pick up",
    kana: "ピック アップ",
    ja: "受け取る・迎えに行く",
    pos: "熟語",
    example: "Where do we pick up our luggage?",
    exampleJa: "荷物はどこで受け取りますか?",
    note: "旅行中いちばん使う句動詞。料理の受け取りも配車の乗車も pick up。",
  },
  {
    id: "vc-air-13",
    group: "airport",
    type: "idiom",
    en: "take off",
    kana: "テイク オフ",
    ja: "離陸する・(服を)脱ぐ",
    pos: "熟語",
    example: "Please take off your shoes and belt.",
    exampleJa: "靴とベルトを外してください。",
    note: "保安検査で必ず聞きます。飛行機なら「離陸する」。",
  },
  {
    id: "vc-air-14",
    group: "airport",
    type: "idiom",
    en: "get through",
    kana: "ゲット スルー",
    ja: "(検査などを)通り抜ける",
    pos: "熟語",
    example: "It took an hour to get through security.",
    exampleJa: "保安検査を抜けるのに1時間かかりました。",
  },

  // --------------------------------------------------------------- transit
  {
    id: "vc-tra-01",
    group: "transit",
    type: "word",
    en: "uptown",
    kana: "アップタウン",
    ja: "北方面(マンハッタンの上手)",
    pos: "名詞・副詞",
    example: "Take the uptown 6 train.",
    exampleJa: "北方面の6番線に乗ってください。",
    note: "NYの地下鉄は行き先が uptown / downtown 表示。ホームが上下線で分かれているので入口を間違えると改札を出る羽目に。",
  },
  {
    id: "vc-tra-02",
    group: "transit",
    type: "word",
    en: "downtown",
    kana: "ダウンタウン",
    ja: "南方面(マンハッタンの下手)",
    pos: "名詞・副詞",
    example: "This platform is for downtown trains only.",
    exampleJa: "このホームは南方面行き専用です。",
    note: "「繁華街」ではなく、NYでは「南方向」。ブルックリン方面も downtown 表示です。",
  },
  {
    id: "vc-tra-03",
    group: "transit",
    type: "word",
    en: "express train",
    kana: "エクスプレス トレイン",
    ja: "急行",
    pos: "名詞",
    example: "The express train skips 23rd Street.",
    exampleJa: "急行は23丁目に止まりません。",
    note: "各駅停車は local train。急行に乗ると数駅飛ばされます。",
  },
  {
    id: "vc-tra-04",
    group: "transit",
    type: "word",
    en: "transfer",
    kana: "トランスファー",
    ja: "乗り換え(する)",
    pos: "名詞・動詞",
    example: "Transfer to the L train at 14th Street.",
    exampleJa: "14丁目でL線に乗り換えてください。",
  },
  {
    id: "vc-tra-05",
    group: "transit",
    type: "word",
    en: "fare",
    kana: "フェア",
    ja: "運賃",
    pos: "名詞",
    example: "The subway fare is the same no matter how far you go.",
    exampleJa: "地下鉄の運賃はどこまで乗っても同じです。",
  },
  {
    id: "vc-tra-06",
    group: "transit",
    type: "word",
    en: "turnstile",
    kana: "ターンスタイル",
    ja: "改札(回転式のバー)",
    pos: "名詞",
    example: "Tap your card on the turnstile.",
    exampleJa: "改札にカードをタッチしてください。",
    note: "OMNY ならクレジットカードやスマホをそのままタップできます。",
  },
  {
    id: "vc-tra-07",
    group: "transit",
    type: "word",
    en: "platform",
    kana: "プラットフォーム",
    ja: "ホーム",
    pos: "名詞",
    example: "Which platform is the A train on?",
    exampleJa: "A線はどのホームですか?",
    note: "日本語の「ホーム」は和製英語。home では通じません。",
  },
  {
    id: "vc-tra-08",
    group: "transit",
    type: "word",
    en: "block",
    kana: "ブロック",
    ja: "街区(交差点から交差点まで)",
    pos: "名詞",
    example: "It's three blocks north of here.",
    exampleJa: "ここから北へ3ブロックです。",
    note: "道案内の基本単位。南北1ブロックは約80m、東西は約280mと長めです。",
  },
  {
    id: "vc-tra-09",
    group: "transit",
    type: "word",
    en: "avenue",
    kana: "アヴェニュー",
    ja: "大通り(南北の通り)",
    pos: "名詞",
    example: "Walk up Fifth Avenue to 42nd Street.",
    exampleJa: "5番街を42丁目まで北へ歩いてください。",
    note: "マンハッタンは南北が avenue、東西が street。住所を聞くときの手がかりになります。",
  },
  {
    id: "vc-tra-10",
    group: "transit",
    type: "word",
    en: "rush hour",
    kana: "ラッシュ アワー",
    ja: "通勤ラッシュの時間帯",
    pos: "名詞",
    example: "Avoid the subway during rush hour.",
    exampleJa: "ラッシュ時の地下鉄は避けましょう。",
  },
  {
    id: "vc-tra-11",
    group: "transit",
    type: "word",
    en: "curb",
    kana: "カーブ",
    ja: "歩道の縁石",
    pos: "名詞",
    example: "Your driver will meet you at the curb.",
    exampleJa: "ドライバーは歩道の縁で待っています。",
    note: "Uber/Lyftの合流地点でよく使われます。道路の「カーブ」は curve。",
  },
  {
    id: "vc-tra-12",
    group: "transit",
    type: "word",
    en: "detour",
    kana: "ディートゥア",
    ja: "迂回(路)",
    pos: "名詞",
    example: "There's a detour because of construction.",
    exampleJa: "工事のため迂回路になっています。",
  },
  {
    id: "vc-tra-13",
    group: "transit",
    type: "idiom",
    en: "get off",
    kana: "ゲット オフ",
    ja: "降りる",
    pos: "熟語",
    example: "Get off at the next stop.",
    exampleJa: "次の駅で降りてください。",
    note: "乗るのは get on(バス・電車)/ get in(タクシー・車)。",
  },
  {
    id: "vc-tra-14",
    group: "transit",
    type: "idiom",
    en: "get on",
    kana: "ゲット オン",
    ja: "乗る",
    pos: "熟語",
    example: "Get on the F train here.",
    exampleJa: "ここでF線に乗ってください。",
  },
  {
    id: "vc-tra-15",
    group: "transit",
    type: "idiom",
    en: "head to",
    kana: "ヘッド トゥ",
    ja: "〜へ向かう",
    pos: "熟語",
    example: "We're heading to Brooklyn after this.",
    exampleJa: "このあとブルックリンへ向かいます。",
  },
  {
    id: "vc-tra-16",
    group: "transit",
    type: "idiom",
    en: "drop off",
    kana: "ドロップ オフ",
    ja: "(人や物を)降ろす・置いていく",
    pos: "熟語",
    example: "Can you drop us off at the corner?",
    exampleJa: "角で降ろしてもらえますか?",
  },
  {
    id: "vc-tra-17",
    group: "transit",
    type: "idiom",
    en: "run late",
    kana: "ラン レイト",
    ja: "予定より遅れている",
    pos: "熟語",
    example: "We're running late for the show.",
    exampleJa: "ショーに遅れそうです。",
  },
  {
    id: "vc-tra-18",
    group: "transit",
    type: "idiom",
    en: "on foot",
    kana: "オン フット",
    ja: "徒歩で",
    pos: "熟語",
    example: "It's about fifteen minutes on foot.",
    exampleJa: "徒歩で15分ほどです。",
  },
  {
    id: "vc-tra-19",
    group: "transit",
    type: "word",
    en: "one-way",
    kana: "ワンウェイ",
    ja: "一方通行の・片道の",
    pos: "形容詞",
    example: "That street is one-way, so we'll go around.",
    exampleJa: "その道は一方通行なので回り込みます。",
  },
  {
    id: "vc-tra-20",
    group: "transit",
    type: "word",
    en: "crosstown",
    kana: "クロスタウン",
    ja: "東西に横断する(バスなど)",
    pos: "形容詞",
    example: "Take the crosstown bus on 42nd Street.",
    exampleJa: "42丁目の東西バスに乗ってください。",
    note: "地下鉄は南北が中心。東西の移動はバスかタクシーが早いことが多いです。",
  },

  // ----------------------------------------------------------------- hotel
  {
    id: "vc-htl-01",
    group: "hotel",
    type: "word",
    en: "front desk",
    kana: "フロント デスク",
    ja: "フロント・受付",
    pos: "名詞",
    example: "Ask the front desk for an extra towel.",
    exampleJa: "タオルの追加はフロントに頼んでください。",
    note: "日本語の「フロント」だけでは通じません。front desk か reception。",
  },
  {
    id: "vc-htl-02",
    group: "hotel",
    type: "word",
    en: "reservation",
    kana: "リザベーション",
    ja: "予約",
    pos: "名詞",
    example: "I have a reservation under Tanaka.",
    exampleJa: "田中の名前で予約しています。",
    note: "レストランでもそのまま使えます。予約名は under + 名字。",
  },
  {
    id: "vc-htl-03",
    group: "hotel",
    type: "word",
    en: "key card",
    kana: "キー カード",
    ja: "カードキー",
    pos: "名詞",
    example: "My key card isn't working.",
    exampleJa: "カードキーが反応しません。",
  },
  {
    id: "vc-htl-04",
    group: "hotel",
    type: "word",
    en: "housekeeping",
    kana: "ハウスキーピング",
    ja: "客室清掃(係)",
    pos: "名詞",
    example: "Could we get housekeeping today?",
    exampleJa: "今日、部屋の清掃をお願いできますか?",
    note: "アメリカのホテルでは清掃係に $2〜5 のチップを枕元に置く習慣があります。",
  },
  {
    id: "vc-htl-05",
    group: "hotel",
    type: "word",
    en: "deposit",
    kana: "ディポジット",
    ja: "保証金・預り金",
    pos: "名詞",
    example: "We'll place a $100 deposit on your card.",
    exampleJa: "カードに100ドルの保証金をお預かりします。",
    note: "チェックイン時にカードへ仮押さえされる金額。チェックアウト後に戻ります。",
  },
  {
    id: "vc-htl-06",
    group: "hotel",
    type: "word",
    en: "amenities",
    kana: "アメニティーズ",
    ja: "備品・館内設備",
    pos: "名詞",
    example: "The gym and the rooftop are free amenities.",
    exampleJa: "ジムと屋上は無料でご利用いただけます。",
  },
  {
    id: "vc-htl-07",
    group: "hotel",
    type: "word",
    en: "vacancy",
    kana: "ヴェイカンシー",
    ja: "空室",
    pos: "名詞",
    example: "The sign says No Vacancy.",
    exampleJa: "看板に「満室」と出ています。",
    note: "小さな宿の看板でよく見ます。No Vacancy = 満室。",
  },
  {
    id: "vc-htl-08",
    group: "hotel",
    type: "word",
    en: "luggage storage",
    kana: "ラゲッジ ストレージ",
    ja: "荷物預かり",
    pos: "名詞",
    example: "Do you have luggage storage after checkout?",
    exampleJa: "チェックアウト後に荷物を預かってもらえますか?",
    note: "最終日に荷物を預けて観光するときの必須表現です。",
  },
  {
    id: "vc-htl-09",
    group: "hotel",
    type: "word",
    en: "wake-up call",
    kana: "ウェイカップ コール",
    ja: "モーニングコール",
    pos: "名詞",
    example: "Can I get a wake-up call at six?",
    exampleJa: "6時にモーニングコールをお願いできますか?",
    note: "morning call は和製英語です。",
  },
  {
    id: "vc-htl-10",
    group: "hotel",
    type: "word",
    en: "complimentary",
    kana: "コンプリメンタリー",
    ja: "無料の(サービスの)",
    pos: "形容詞",
    example: "Breakfast is complimentary.",
    exampleJa: "朝食は無料です。",
    note: "ホテルの案内で free よりよく使われる語。見たら「無料」と読めればOK。",
  },
  {
    id: "vc-htl-11",
    group: "hotel",
    type: "idiom",
    en: "check out",
    kana: "チェック アウト",
    ja: "チェックアウトする・見てみる",
    pos: "熟語",
    example: "What time do we have to check out?",
    exampleJa: "何時までにチェックアウトですか?",
    note: "「見てみる」の意味も頻出:You should check out that bakery.(あのパン屋、行ってみて)",
  },
  {
    id: "vc-htl-12",
    group: "hotel",
    type: "idiom",
    en: "settle the bill",
    kana: "セトル ザ ビル",
    ja: "支払いを済ませる",
    pos: "熟語",
    example: "I'd like to settle the bill now.",
    exampleJa: "今、支払いを済ませたいのですが。",
  },
  {
    id: "vc-htl-13",
    group: "hotel",
    type: "idiom",
    en: "freshen up",
    kana: "フレッシュン アップ",
    ja: "身支度を整える・さっぱりする",
    pos: "熟語",
    example: "Let's freshen up and go out.",
    exampleJa: "身支度をして出かけましょう。",
  },
  {
    id: "vc-htl-14",
    group: "hotel",
    type: "idiom",
    en: "be all set",
    kana: "ビー オール セット",
    ja: "準備が整っている・もう大丈夫",
    pos: "熟語",
    example: "You're all set — here's your key card.",
    exampleJa: "手続きは完了です。こちらがカードキーです。",
    note: "ホテルでもレジでも決まり文句。You're all set. と言われたら「終わりました」の意味。",
  },

  // ------------------------------------------------------------------ food
  {
    id: "vc-fod-01",
    group: "food",
    type: "word",
    en: "server",
    kana: "サーバー",
    ja: "接客係(ウェイター・ウェイトレス)",
    pos: "名詞",
    example: "Your server will be right with you.",
    exampleJa: "担当の者がすぐに参ります。",
    note: "waiter/waitress より server が今の標準的な呼び方です。",
  },
  {
    id: "vc-fod-02",
    group: "food",
    type: "word",
    en: "appetizer",
    kana: "アペタイザー",
    ja: "前菜",
    pos: "名詞",
    example: "Would you like to start with an appetizer?",
    exampleJa: "まず前菜はいかがですか?",
    note: "starter とも。小皿で分け合うなら shareable と書かれています。",
  },
  {
    id: "vc-fod-03",
    group: "food",
    type: "word",
    en: "entrée",
    kana: "アントレイ",
    ja: "メインディッシュ",
    pos: "名詞",
    example: "What would you like for your entrée?",
    exampleJa: "メインは何になさいますか?",
    note: "アメリカでは「主菜」。フランス語の前菜とは逆なので注意。",
  },
  {
    id: "vc-fod-04",
    group: "food",
    type: "word",
    en: "side",
    kana: "サイド",
    ja: "つけ合わせ・副菜",
    pos: "名詞",
    example: "Which side would you like — fries or salad?",
    exampleJa: "つけ合わせはポテトとサラダ、どちらにしますか?",
  },
  {
    id: "vc-fod-05",
    group: "food",
    type: "word",
    en: "refill",
    kana: "リフィル",
    ja: "おかわり(飲み物の注ぎ足し)",
    pos: "名詞・動詞",
    example: "Free refills on soda and coffee.",
    exampleJa: "ソーダとコーヒーはおかわり無料です。",
    note: "ダイナーではコーヒーを勝手に注ぎ足してくれることも。断るなら I'm good, thanks.",
  },
  {
    id: "vc-fod-06",
    group: "food",
    type: "word",
    en: "check",
    kana: "チェック",
    ja: "お会計・伝票",
    pos: "名詞",
    example: "Could we get the check, please?",
    exampleJa: "お会計をお願いできますか?",
    note: "アメリカは check、イギリスは bill。テーブルで支払うのが基本です。",
  },
  {
    id: "vc-fod-07",
    group: "food",
    type: "word",
    en: "takeout",
    kana: "テイクアウト",
    ja: "持ち帰り",
    pos: "名詞",
    example: "Is this for takeout?",
    exampleJa: "お持ち帰りですか?",
    note: "カウンターでは For here or to go?(店内かお持ち帰りか)と聞かれます。",
  },
  {
    id: "vc-fod-08",
    group: "food",
    type: "word",
    en: "leftovers",
    kana: "レフトオーバーズ",
    ja: "食べ残し・残り物",
    pos: "名詞",
    example: "Would you like a box for your leftovers?",
    exampleJa: "残りをお包みしましょうか?",
    note: "NYは量が多いので持ち帰りが普通。Can I get a box? で通じます。",
  },
  {
    id: "vc-fod-09",
    group: "food",
    type: "word",
    en: "tap water",
    kana: "タップ ウォーター",
    ja: "水道水(無料の水)",
    pos: "名詞",
    example: "Just tap water, please.",
    exampleJa: "お水(水道水)をお願いします。",
    note: "黙っていると有料のボトル水が来ることがあります。無料なのは tap water。",
  },
  {
    id: "vc-fod-10",
    group: "food",
    type: "word",
    en: "medium rare",
    kana: "ミディアム レア",
    ja: "ミディアムレア(肉の焼き加減)",
    pos: "名詞",
    example: "How would you like your steak? — Medium rare, please.",
    exampleJa: "焼き加減はいかがしますか? — ミディアムレアでお願いします。",
    note: "順に rare / medium rare / medium / medium well / well done。",
  },
  {
    id: "vc-fod-11",
    group: "food",
    type: "word",
    en: "deli",
    kana: "デリ",
    ja: "デリ(総菜店・サンドイッチ店)",
    pos: "名詞",
    example: "Let's grab a sandwich at the deli.",
    exampleJa: "デリでサンドイッチを買いましょう。",
    note: "NYの朝食の定番。bodega は24時間開いている小さな雑貨店兼デリです。",
  },
  {
    id: "vc-fod-12",
    group: "food",
    type: "word",
    en: "brunch",
    kana: "ブランチ",
    ja: "ブランチ(朝食兼昼食)",
    pos: "名詞",
    example: "Brunch is served until 3 p.m. on weekends.",
    exampleJa: "週末のブランチは午後3時までです。",
    note: "NYの週末文化。人気店は行列なので予約か早めの時間が安心です。",
  },
  {
    id: "vc-fod-13",
    group: "food",
    type: "word",
    en: "happy hour",
    kana: "ハッピー アワー",
    ja: "割引時間帯(夕方の酒・軽食)",
    pos: "名詞",
    example: "Happy hour is from four to seven.",
    exampleJa: "ハッピーアワーは4時から7時までです。",
  },
  {
    id: "vc-fod-14",
    group: "food",
    type: "word",
    en: "allergic",
    kana: "アラジック",
    ja: "アレルギーがある",
    pos: "形容詞",
    example: "I'm allergic to peanuts.",
    exampleJa: "ピーナッツのアレルギーがあります。",
    note: "命に関わる話。注文前にはっきり伝えましょう。名詞は allergy(アラジー)。",
  },
  {
    id: "vc-fod-15",
    group: "food",
    type: "idiom",
    en: "on the side",
    kana: "オン ザ サイド",
    ja: "別添えで",
    pos: "表現",
    example: "Can I get the dressing on the side?",
    exampleJa: "ドレッシングは別添えにしてもらえますか?",
    note: "苦手なものを避けたいときの魔法の一言。",
  },
  {
    id: "vc-fod-16",
    group: "food",
    type: "word",
    en: "walk-in",
    kana: "ウォークイン",
    ja: "予約なしの来店",
    pos: "名詞",
    example: "We take walk-ins at the bar.",
    exampleJa: "バーカウンターなら予約なしでも大丈夫です。",
  },
  {
    id: "vc-fod-17",
    group: "food",
    type: "idiom",
    en: "grab a bite",
    kana: "グラブ ア バイト",
    ja: "軽く食べる",
    pos: "熟語",
    example: "Let's grab a bite before the show.",
    exampleJa: "ショーの前に軽く食べましょう。",
  },
  {
    id: "vc-fod-18",
    group: "food",
    type: "idiom",
    en: "to go",
    kana: "トゥ ゴー",
    ja: "持ち帰りで",
    pos: "熟語",
    example: "Two coffees to go, please.",
    exampleJa: "コーヒー2つ、持ち帰りでお願いします。",
    note: "店内なら for here。これだけでレジのやり取りが半分片づきます。",
  },
  {
    id: "vc-fod-19",
    group: "food",
    type: "idiom",
    en: "split the check",
    kana: "スプリット ザ チェック",
    ja: "割り勘にする",
    pos: "熟語",
    example: "Could we split the check?",
    exampleJa: "会計を分けてもらえますか?",
    note: "カードを2枚渡して Split it evenly, please. でも通じます。",
  },
  {
    id: "vc-fod-20",
    group: "food",
    type: "idiom",
    en: "be out of",
    kana: "ビー アウト オブ",
    ja: "(在庫を)切らしている",
    pos: "熟語",
    example: "Sorry, we're out of the lobster roll.",
    exampleJa: "申し訳ありません、ロブスターロールは品切れです。",
  },
  {
    id: "vc-fod-21",
    group: "food",
    type: "idiom",
    en: "help yourself",
    kana: "ヘルプ ユアセルフ",
    ja: "ご自由にどうぞ",
    pos: "熟語",
    example: "Napkins are over there — help yourself.",
    exampleJa: "ナプキンはあちらです。ご自由にどうぞ。",
  },
  {
    id: "vc-fod-22",
    group: "food",
    type: "idiom",
    en: "I'm good",
    kana: "アイム グッド",
    ja: "けっこうです(もう十分)",
    pos: "熟語",
    example: "More coffee? — I'm good, thanks.",
    exampleJa: "コーヒーのおかわりは? — 大丈夫です、ありがとう。",
    note: "断り文句として毎日使います。No の代わりに角が立ちません。",
  },

  // -------------------------------------------------------------- shopping
  {
    id: "vc-shp-01",
    group: "shopping",
    type: "word",
    en: "fitting room",
    kana: "フィッティング ルーム",
    ja: "試着室",
    pos: "名詞",
    example: "The fitting rooms are in the back.",
    exampleJa: "試着室は奥にあります。",
    note: "dressing room とも言います。",
  },
  {
    id: "vc-shp-02",
    group: "shopping",
    type: "word",
    en: "receipt",
    kana: "リスィート",
    ja: "レシート・領収書",
    pos: "名詞",
    example: "Keep your receipt for the refund.",
    exampleJa: "返金にはレシートが必要です。",
    note: "p は発音しません。返品には必須なので旅行中は捨てないこと。",
  },
  {
    id: "vc-shp-03",
    group: "shopping",
    type: "word",
    en: "refund",
    kana: "リファンド",
    ja: "返金",
    pos: "名詞・動詞",
    example: "Can I get a refund on this?",
    exampleJa: "これを返金してもらえますか?",
    note: "交換は exchange。アメリカは返品に寛容で、多くの店が30日以内ならOK。",
  },
  {
    id: "vc-shp-04",
    group: "shopping",
    type: "word",
    en: "sales tax",
    kana: "セールス タックス",
    ja: "消費税(売上税)",
    pos: "名詞",
    example: "Sales tax is added at the register.",
    exampleJa: "消費税はレジで加算されます。",
    note: "NY市は約8.875%。値札は税抜きなので会計は必ず高くなります。衣料品は110ドル未満なら非課税。",
  },
  {
    id: "vc-shp-05",
    group: "shopping",
    type: "idiom",
    en: "out of stock",
    kana: "アウト オブ ストック",
    ja: "在庫切れ",
    pos: "表現",
    example: "That size is out of stock.",
    exampleJa: "そのサイズは在庫切れです。",
  },
  {
    id: "vc-shp-06",
    group: "shopping",
    type: "idiom",
    en: "on sale",
    kana: "オン セール",
    ja: "セール中で",
    pos: "表現",
    example: "Everything on this rack is on sale.",
    exampleJa: "このラックの商品はすべてセール中です。",
    note: "for sale は「売り物」。on sale は「値引き中」です。",
  },
  {
    id: "vc-shp-07",
    group: "shopping",
    type: "word",
    en: "clearance",
    kana: "クリアランス",
    ja: "在庫処分(の値下げ)",
    pos: "名詞",
    example: "Clearance items are final sale.",
    exampleJa: "処分品は返品不可です。",
    note: "final sale と書かれていたら返品・交換できません。",
  },
  {
    id: "vc-shp-08",
    group: "shopping",
    type: "word",
    en: "cashier",
    kana: "キャシャー",
    ja: "レジ係",
    pos: "名詞",
    example: "Please pay the cashier at the front.",
    exampleJa: "前方のレジでお支払いください。",
    note: "レジそのものは register や checkout。",
  },
  {
    id: "vc-shp-09",
    group: "shopping",
    type: "word",
    en: "gift receipt",
    kana: "ギフト リスィート",
    ja: "金額なしの贈り物用レシート",
    pos: "名詞",
    example: "Could I get a gift receipt?",
    exampleJa: "ギフト用のレシートをもらえますか?",
    note: "お土産に添えると、相手がサイズ交換できます。",
  },
  {
    id: "vc-shp-10",
    group: "shopping",
    type: "word",
    en: "aisle",
    kana: "アイル",
    ja: "(店の)通路・売り場の列",
    pos: "名詞",
    example: "Snacks are in aisle five.",
    exampleJa: "お菓子は5番通路です。",
    note: "スーパーで場所を聞くときの答えがこれ。Which aisle? と聞けます。",
  },
  {
    id: "vc-shp-11",
    group: "shopping",
    type: "idiom",
    en: "try on",
    kana: "トライ オン",
    ja: "試着する",
    pos: "熟語",
    example: "Can I try this on?",
    exampleJa: "これ、試着してもいいですか?",
    note: "目的語が代名詞なら try it on の語順になります。",
  },
  {
    id: "vc-shp-12",
    group: "shopping",
    type: "idiom",
    en: "just looking",
    kana: "ジャスト ルッキング",
    ja: "見ているだけです",
    pos: "熟語",
    example: "Can I help you find anything? — I'm just looking, thanks.",
    exampleJa: "何かお探しですか? — 見ているだけです、ありがとう。",
    note: "声をかけられたときの定番の返し。これで放っておいてもらえます。",
  },
  {
    id: "vc-shp-13",
    group: "shopping",
    type: "idiom",
    en: "ring up",
    kana: "リング アップ",
    ja: "レジで会計する",
    pos: "熟語",
    example: "I can ring you up over here.",
    exampleJa: "こちらのレジでお会計できます。",
    note: "店員側の言い方。呼ばれたらそのレジへ進みます。",
  },
  {
    id: "vc-shp-14",
    group: "shopping",
    type: "idiom",
    en: "sold out",
    kana: "ソールド アウト",
    ja: "売り切れ",
    pos: "熟語",
    example: "The tickets are sold out for tonight.",
    exampleJa: "今夜の券は売り切れです。",
  },
  {
    id: "vc-shp-15",
    group: "shopping",
    type: "idiom",
    en: "look around",
    kana: "ルック アラウンド",
    ja: "店内を見て回る",
    pos: "熟語",
    example: "Let's look around a little more.",
    exampleJa: "もう少し見て回りましょう。",
  },
  {
    id: "vc-shp-16",
    group: "shopping",
    type: "idiom",
    en: "hold on to",
    kana: "ホールド オン トゥ",
    ja: "手放さず持っておく",
    pos: "熟語",
    example: "Hold on to your receipt.",
    exampleJa: "レシートは持っておいてください。",
  },

  // ----------------------------------------------------------------- money
  {
    id: "vc-mny-01",
    group: "money",
    type: "word",
    en: "tip",
    kana: "チップ",
    ja: "チップ(心付け)",
    pos: "名詞・動詞",
    example: "We usually tip around 20 percent.",
    exampleJa: "だいたい20%のチップを渡します。",
    note: "NYのレストランは18〜20%が目安。伝票の下に候補額が印字されています。",
  },
  {
    id: "vc-mny-02",
    group: "money",
    type: "word",
    en: "gratuity",
    kana: "グラチュイティ",
    ja: "サービス料・チップ",
    pos: "名詞",
    example: "An 18% gratuity is included for parties of six or more.",
    exampleJa: "6名以上のお客様には18%のサービス料が含まれます。",
    note: "gratuity included と書いてあれば追加のチップは不要です。",
  },
  {
    id: "vc-mny-03",
    group: "money",
    type: "word",
    en: "change",
    kana: "チェンジ",
    ja: "おつり・小銭",
    pos: "名詞",
    example: "Keep the change.",
    exampleJa: "おつりは取っておいてください。",
    note: "タクシーでチップ代わりによく使う一言。",
  },
  {
    id: "vc-mny-04",
    group: "money",
    type: "word",
    en: "bill",
    kana: "ビル",
    ja: "紙幣",
    pos: "名詞",
    example: "Could you give me some small bills?",
    exampleJa: "小額紙幣に崩してもらえますか?",
    note: "チップ用に $1 札を多めに持っておくと毎日が楽になります。",
  },
  {
    id: "vc-mny-05",
    group: "money",
    type: "idiom",
    en: "cash only",
    kana: "キャッシュ オンリー",
    ja: "現金のみ",
    pos: "表現",
    example: "This food cart is cash only.",
    exampleJa: "この屋台は現金のみです。",
    note: "屋台や古い店で見ます。逆に cashless(カードのみ)の店も増えています。",
  },
  {
    id: "vc-mny-06",
    group: "money",
    type: "word",
    en: "contactless",
    kana: "コンタクトレス",
    ja: "タッチ決済の",
    pos: "形容詞",
    example: "We take contactless payments.",
    exampleJa: "タッチ決済が使えます。",
    note: "地下鉄の OMNY もこれ。Just tap. と言われたらかざすだけ。",
  },
  {
    id: "vc-mny-07",
    group: "money",
    type: "word",
    en: "surcharge",
    kana: "サーチャージ",
    ja: "追加料金",
    pos: "名詞",
    example: "There's a small surcharge for credit cards.",
    exampleJa: "クレジットカードには少額の追加料金がかかります。",
  },
  {
    id: "vc-mny-08",
    group: "money",
    type: "word",
    en: "pricey",
    kana: "プライシー",
    ja: "高い・割高な",
    pos: "形容詞",
    example: "That rooftop bar is pricey but worth it.",
    exampleJa: "あの屋上バーは高いけれど価値があります。",
  },
  {
    id: "vc-mny-09",
    group: "money",
    type: "idiom",
    en: "pay for",
    kana: "ペイ フォー",
    ja: "〜の代金を払う",
    pos: "熟語",
    example: "I'll pay for the tickets.",
    exampleJa: "チケット代は私が払います。",
  },
  {
    id: "vc-mny-10",
    group: "money",
    type: "idiom",
    en: "pick up the tab",
    kana: "ピック アップ ザ タブ",
    ja: "支払いを持つ・おごる",
    pos: "熟語",
    example: "Let me pick up the tab tonight.",
    exampleJa: "今夜は私がおごります。",
  },
  {
    id: "vc-mny-11",
    group: "money",
    type: "idiom",
    en: "break a twenty",
    kana: "ブレイク ア トゥエンティ",
    ja: "20ドル札を崩す",
    pos: "熟語",
    example: "Can you break a twenty?",
    exampleJa: "20ドル札を崩してもらえますか?",
  },
  {
    id: "vc-mny-12",
    group: "money",
    type: "idiom",
    en: "be worth it",
    kana: "ビー ワース イット",
    ja: "その価値がある",
    pos: "熟語",
    example: "The view from the top is worth it.",
    exampleJa: "上からの眺めは払う価値があります。",
  },

  // ----------------------------------------------------------- sightseeing
  {
    id: "vc-sgt-01",
    group: "sightseeing",
    type: "word",
    en: "admission",
    kana: "アドミッション",
    ja: "入場料・入場",
    pos: "名詞",
    example: "Admission is $25 for adults.",
    exampleJa: "大人の入場料は25ドルです。",
    note: "美術館の入口の掲示でよく見ます。寄付制なら pay what you wish。",
  },
  {
    id: "vc-sgt-02",
    group: "sightseeing",
    type: "word",
    en: "timed entry",
    kana: "タイムド エントリー",
    ja: "時間指定の入場",
    pos: "名詞",
    example: "This ticket is timed entry at 2 p.m.",
    exampleJa: "このチケットは午後2時の時間指定入場です。",
    note: "自由の女神や展望台は時間指定が基本。遅れると入れないこともあります。",
  },
  {
    id: "vc-sgt-03",
    group: "sightseeing",
    type: "word",
    en: "observation deck",
    kana: "オブザベーション デック",
    ja: "展望台",
    pos: "名詞",
    example: "The observation deck closes at midnight.",
    exampleJa: "展望台は深夜0時に閉まります。",
  },
  {
    id: "vc-sgt-04",
    group: "sightseeing",
    type: "word",
    en: "exhibit",
    kana: "エグジビット",
    ja: "展示",
    pos: "名詞",
    example: "The special exhibit needs a separate ticket.",
    exampleJa: "特別展は別料金のチケットが必要です。",
  },
  {
    id: "vc-sgt-05",
    group: "sightseeing",
    type: "word",
    en: "landmark",
    kana: "ランドマーク",
    ja: "名所・目印になる建物",
    pos: "名詞",
    example: "That building is a city landmark.",
    exampleJa: "あの建物は市の名所です。",
  },
  {
    id: "vc-sgt-06",
    group: "sightseeing",
    type: "word",
    en: "audio guide",
    kana: "オーディオ ガイド",
    ja: "音声ガイド",
    pos: "名詞",
    example: "Is the audio guide available in Japanese?",
    exampleJa: "音声ガイドに日本語はありますか?",
  },
  {
    id: "vc-sgt-07",
    group: "sightseeing",
    type: "word",
    en: "ticket booth",
    kana: "チケット ブース",
    ja: "チケット売り場",
    pos: "名詞",
    example: "The ticket booth is by the entrance.",
    exampleJa: "チケット売り場は入口のそばです。",
    note: "ブロードウェイ当日券の TKTS もこの booth の一種です。",
  },
  {
    id: "vc-sgt-08",
    group: "sightseeing",
    type: "word",
    en: "matinee",
    kana: "マティネイ",
    ja: "昼公演",
    pos: "名詞",
    example: "We're seeing the Wednesday matinee.",
    exampleJa: "水曜の昼公演を観ます。",
    note: "ブロードウェイは水・土・日に昼公演があり、夜より取りやすいことが多いです。",
  },
  {
    id: "vc-sgt-09",
    group: "sightseeing",
    type: "word",
    en: "line",
    kana: "ライン",
    ja: "行列",
    pos: "名詞",
    example: "The line starts around the corner.",
    exampleJa: "列は角を曲がったところからです。",
    note: "アメリカは line、イギリスは queue。「並ぶ」は wait in line。",
  },
  {
    id: "vc-sgt-10",
    group: "sightseeing",
    type: "idiom",
    en: "stop by",
    kana: "ストップ バイ",
    ja: "立ち寄る",
    pos: "熟語",
    example: "Let's stop by the gift shop on the way out.",
    exampleJa: "帰りにお土産売り場に寄りましょう。",
    note: "おすすめを教わるときは You should stop by ... の形でよく出てきます。",
  },
  {
    id: "vc-sgt-11",
    group: "sightseeing",
    type: "idiom",
    en: "line up",
    kana: "ライン アップ",
    ja: "列に並ぶ",
    pos: "熟語",
    example: "Please line up along the wall.",
    exampleJa: "壁に沿って並んでください。",
  },
  {
    id: "vc-sgt-12",
    group: "sightseeing",
    type: "idiom",
    en: "take a picture of",
    kana: "テイク ア ピクチャー オブ",
    ja: "〜の写真を撮る",
    pos: "熟語",
    example: "Could you take a picture of us?",
    exampleJa: "私たちの写真を撮ってもらえますか?",
    note: "自分たちが写る写真は of us。with us だと「一緒に写る」意味になります。",
  },
  {
    id: "vc-sgt-13",
    group: "sightseeing",
    type: "idiom",
    en: "run out of",
    kana: "ラン アウト オブ",
    ja: "〜を使い果たす",
    pos: "熟語",
    example: "My phone is running out of battery.",
    exampleJa: "スマホの充電が切れそうです。",
  },
  {
    id: "vc-sgt-14",
    group: "sightseeing",
    type: "idiom",
    en: "show up",
    kana: "ショウ アップ",
    ja: "現れる・顔を出す",
    pos: "熟語",
    example: "Show up fifteen minutes before the tour.",
    exampleJa: "ツアーの15分前には来てください。",
  },

  // ---------------------------------------------------------------- street
  {
    id: "vc-str-01",
    group: "street",
    type: "word",
    en: "restroom",
    kana: "レストルーム",
    ja: "お手洗い",
    pos: "名詞",
    example: "Is there a restroom I can use?",
    exampleJa: "使えるお手洗いはありますか?",
    note: "toilet は便器そのものを指すので、人には restroom か bathroom と言います。",
  },
  {
    id: "vc-str-02",
    group: "street",
    type: "idiom",
    en: "out of order",
    kana: "アウト オブ オーダー",
    ja: "故障中",
    pos: "表現",
    example: "The elevator is out of order.",
    exampleJa: "エレベーターは故障中です。",
    note: "地下鉄のエレベーターや券売機の貼り紙でよく見ます。",
  },
  {
    id: "vc-str-03",
    group: "street",
    type: "idiom",
    en: "out of service",
    kana: "アウト オブ サービス",
    ja: "回送・運休中",
    pos: "表現",
    example: "That bus is out of service.",
    exampleJa: "あのバスは回送中です。",
  },
  {
    id: "vc-str-04",
    group: "street",
    type: "word",
    en: "crosswalk",
    kana: "クロスウォーク",
    ja: "横断歩道",
    pos: "名詞",
    example: "Use the crosswalk at the light.",
    exampleJa: "信号のある横断歩道を渡ってください。",
  },
  {
    id: "vc-str-05",
    group: "street",
    type: "word",
    en: "pedestrian",
    kana: "ペデストリアン",
    ja: "歩行者",
    pos: "名詞",
    example: "This street is for pedestrians only.",
    exampleJa: "この通りは歩行者専用です。",
    note: "タイムズスクエアの一部は pedestrian plaza(歩行者広場)です。",
  },
  {
    id: "vc-str-06",
    group: "street",
    type: "word",
    en: "sidewalk",
    kana: "サイドウォーク",
    ja: "歩道",
    pos: "名詞",
    example: "Stay on the sidewalk.",
    exampleJa: "歩道から出ないでください。",
  },
  {
    id: "vc-str-07",
    group: "street",
    type: "idiom",
    en: "do not enter",
    kana: "ドゥ ノット エンター",
    ja: "立入禁止",
    pos: "表現",
    example: "The sign says Do Not Enter.",
    exampleJa: "「立入禁止」と表示されています。",
  },
  {
    id: "vc-str-08",
    group: "street",
    type: "idiom",
    en: "no standing",
    kana: "ノー スタンディング",
    ja: "停車禁止(道路標識)",
    pos: "表現",
    example: "No Standing means the car can't wait there.",
    exampleJa: "No Standing は、そこで車が待てないという意味です。",
    note: "「立ち止まるな」ではありません。配車アプリで合流場所を決めるときに効いてきます。",
  },
  {
    id: "vc-str-09",
    group: "street",
    type: "idiom",
    en: "wet floor",
    kana: "ウェット フロア",
    ja: "床が濡れています(足元注意)",
    pos: "表現",
    example: "Careful — wet floor.",
    exampleJa: "足元にご注意ください。床が濡れています。",
  },
  {
    id: "vc-str-10",
    group: "street",
    type: "word",
    en: "emergency exit",
    kana: "エマージェンシー エグジット",
    ja: "非常口",
    pos: "名詞",
    example: "The emergency exit is at the end of the hall.",
    exampleJa: "非常口は廊下の突き当たりです。",
  },
  {
    id: "vc-str-11",
    group: "street",
    type: "idiom",
    en: "closed for maintenance",
    kana: "クローズド フォー メンテナンス",
    ja: "整備のため閉鎖中",
    pos: "表現",
    example: "The rooftop is closed for maintenance today.",
    exampleJa: "屋上は本日、整備のため閉鎖中です。",
  },
  {
    id: "vc-str-12",
    group: "street",
    type: "word",
    en: "service change",
    kana: "サービス チェンジ",
    ja: "運行変更(地下鉄の案内)",
    pos: "名詞",
    example: "Weekend service change: the C train is not running.",
    exampleJa: "週末の運行変更:C線は運休です。",
    note: "週末の工事で路線がよく変わります。駅の黄色い貼り紙がこれ。",
  },
  {
    id: "vc-str-13",
    group: "street",
    type: "idiom",
    en: "uptown & Bronx",
    kana: "アップタウン アンド ブロンクス",
    ja: "北方面・ブロンクス方面(入口表示)",
    pos: "表現",
    example: "This entrance says Uptown & Bronx.",
    exampleJa: "この入口は北方面・ブロンクス方面です。",
    note: "地下鉄の入口はホームごとに分かれています。逆方向に入ると一度出る必要があることも。",
  },
  {
    id: "vc-str-14",
    group: "street",
    type: "idiom",
    en: "no smoking",
    kana: "ノー スモーキング",
    ja: "禁煙",
    pos: "表現",
    example: "No smoking anywhere in the park.",
    exampleJa: "公園内は全面禁煙です。",
    note: "NY市は公園・ビーチ・レストランなど屋外でも禁煙の場所が多いです。",
  },
  {
    id: "vc-str-15",
    group: "street",
    type: "word",
    en: "pull",
    kana: "プル",
    ja: "引く(ドアの表示)",
    pos: "動詞",
    example: "The door says pull, not push.",
    exampleJa: "そのドアは押すのではなく引くと書いてあります。",
    note: "押すは push。小さな店のドアで毎日見かけます。",
  },
  {
    id: "vc-str-16",
    group: "street",
    type: "idiom",
    en: "watch out",
    kana: "ウォッチ アウト",
    ja: "気をつけて!",
    pos: "熟語",
    example: "Watch out — bike lane!",
    exampleJa: "気をつけて、自転車レーンだよ!",
    note: "NYの自転車は速く、車道側から来ます。渡る前に左右の確認を。",
  },

  // ------------------------------------------------------------- smalltalk
  {
    id: "vc-tlk-01",
    group: "smalltalk",
    type: "idiom",
    en: "How's it going?",
    kana: "ハウズ イット ゴーイング",
    ja: "調子はどう?(軽いあいさつ)",
    pos: "熟語",
    example: "Hey, how's it going?",
    exampleJa: "やあ、調子はどう?",
    note: "答えは Good, thanks. How about you? で十分。深い意味はありません。",
  },
  {
    id: "vc-tlk-02",
    group: "smalltalk",
    type: "idiom",
    en: "no worries",
    kana: "ノー ワリーズ",
    ja: "気にしないで・大丈夫",
    pos: "熟語",
    example: "Sorry I'm late! — No worries.",
    exampleJa: "遅れてごめん! — 気にしないで。",
  },
  {
    id: "vc-tlk-03",
    group: "smalltalk",
    type: "idiom",
    en: "sure thing",
    kana: "シュア スィング",
    ja: "もちろん・いいですよ",
    pos: "熟語",
    example: "Could I get some water? — Sure thing.",
    exampleJa: "お水をもらえますか? — もちろんです。",
  },
  {
    id: "vc-tlk-04",
    group: "smalltalk",
    type: "idiom",
    en: "my bad",
    kana: "マイ バッド",
    ja: "ごめん、私のミス",
    pos: "熟語",
    example: "My bad — I thought this was our table.",
    exampleJa: "ごめんなさい、ここが自分たちの席だと思って。",
  },
  {
    id: "vc-tlk-05",
    group: "smalltalk",
    type: "idiom",
    en: "have a good one",
    kana: "ハブ ア グッド ワン",
    ja: "よい1日を(別れのあいさつ)",
    pos: "熟語",
    example: "Thanks, have a good one!",
    exampleJa: "ありがとう、よい1日を!",
    note: "レジや運転手と別れるときの定番。You too! と返せば完璧です。",
  },
  {
    id: "vc-tlk-06",
    group: "smalltalk",
    type: "idiom",
    en: "appreciate it",
    kana: "アプリシエイト イット",
    ja: "助かります・ありがとう",
    pos: "熟語",
    example: "I appreciate it.",
    exampleJa: "ありがとうございます、助かります。",
    note: "Thank you より少しあらたまった感謝。道を教えてもらったときに。",
  },
  {
    id: "vc-tlk-07",
    group: "smalltalk",
    type: "idiom",
    en: "go ahead",
    kana: "ゴー アヘッド",
    ja: "どうぞ(お先に)",
    pos: "熟語",
    example: "Go ahead, I'm not in a hurry.",
    exampleJa: "お先にどうぞ、急いでいないので。",
  },
  {
    id: "vc-tlk-08",
    group: "smalltalk",
    type: "idiom",
    en: "hang on",
    kana: "ハング オン",
    ja: "ちょっと待って",
    pos: "熟語",
    example: "Hang on, let me check the map.",
    exampleJa: "ちょっと待って、地図を見てみます。",
  },
  {
    id: "vc-tlk-09",
    group: "smalltalk",
    type: "idiom",
    en: "sounds good",
    kana: "サウンズ グッド",
    ja: "いいですね(それで行きましょう)",
    pos: "熟語",
    example: "Meet at seven? — Sounds good.",
    exampleJa: "7時に待ち合わせ? — いいですね。",
  },
  {
    id: "vc-tlk-10",
    group: "smalltalk",
    type: "idiom",
    en: "excuse me",
    kana: "エクスキューズ ミー",
    ja: "すみません(呼びかけ・前を通るとき)",
    pos: "熟語",
    example: "Excuse me, is this seat taken?",
    exampleJa: "すみません、この席は空いていますか?",
    note: "人に声をかける第一声。ぶつかった後の謝罪は Sorry。",
  },
  {
    id: "vc-tlk-11",
    group: "smalltalk",
    type: "word",
    en: "awesome",
    kana: "オーサム",
    ja: "最高だね・すごくいい",
    pos: "形容詞",
    example: "That view was awesome.",
    exampleJa: "あの景色は最高でした。",
  },
  {
    id: "vc-tlk-12",
    group: "smalltalk",
    type: "word",
    en: "spot",
    kana: "スポット",
    ja: "(お気に入りの)場所・店",
    pos: "名詞",
    example: "This is my favorite coffee spot.",
    exampleJa: "ここが私のお気に入りのコーヒー店です。",
    note: "観光地は tourist spot ではなく tourist attraction と言うのが自然です。",
  },
  {
    id: "vc-tlk-13",
    group: "smalltalk",
    type: "idiom",
    en: "be from",
    kana: "ビー フロム",
    ja: "〜の出身である",
    pos: "熟語",
    example: "Where are you from? — We're from Japan.",
    exampleJa: "どちらから? — 日本から来ました。",
    note: "雑談で必ず聞かれます。答えたあと How about you? と返すと会話が続きます。",
  },
  {
    id: "vc-tlk-14",
    group: "smalltalk",
    type: "idiom",
    en: "first time",
    kana: "ファースト タイム",
    ja: "初めて",
    pos: "熟語",
    example: "It's our first time in New York.",
    exampleJa: "ニューヨークは初めてです。",
    note: "これを言うとおすすめを教えてもらえることが多いです。",
  },

  // --------------------------------------------------------------- trouble
  {
    id: "vc-trb-01",
    group: "trouble",
    type: "word",
    en: "lost and found",
    kana: "ロスト アンド ファウンド",
    ja: "遺失物取扱所",
    pos: "名詞",
    example: "Is there a lost and found here?",
    exampleJa: "ここに遺失物取扱所はありますか?",
  },
  {
    id: "vc-trb-02",
    group: "trouble",
    type: "word",
    en: "pickpocket",
    kana: "ピックポケット",
    ja: "スリ",
    pos: "名詞",
    example: "Watch for pickpockets in crowded places.",
    exampleJa: "人混みではスリに注意してください。",
    note: "地下鉄やタイムズスクエアの注意書きで見ます。かばんは前で持つのが基本。",
  },
  {
    id: "vc-trb-03",
    group: "trouble",
    type: "word",
    en: "scam",
    kana: "スキャム",
    ja: "詐欺・ぼったくり",
    pos: "名詞",
    example: "That CD giveaway is a scam.",
    exampleJa: "あのCD配りは詐欺(有料請求)です。",
    note: "「無料」と渡してきて後から代金を求める手口。受け取らないのが一番です。",
  },
  {
    id: "vc-trb-04",
    group: "trouble",
    type: "word",
    en: "pharmacy",
    kana: "ファーマシー",
    ja: "薬局",
    pos: "名詞",
    example: "There's a pharmacy on the corner.",
    exampleJa: "角に薬局があります。",
    note: "CVS や Walgreens が街中にあります。drugstore もほぼ同じ意味。",
  },
  {
    id: "vc-trb-05",
    group: "trouble",
    type: "word",
    en: "urgent care",
    kana: "アージェント ケア",
    ja: "救急外来より軽い診療所",
    pos: "名詞",
    example: "Urgent care is cheaper than the ER.",
    exampleJa: "緊急診療所は救急外来より安く済みます。",
    note: "軽い体調不良ならまずここ。ER(救急外来)は待ち時間も費用も大きいです。",
  },
  {
    id: "vc-trb-06",
    group: "trouble",
    type: "word",
    en: "prescription",
    kana: "プリスクリプション",
    ja: "処方箋",
    pos: "名詞",
    example: "You'll need a prescription for that.",
    exampleJa: "それには処方箋が必要です。",
  },
  {
    id: "vc-trb-07",
    group: "trouble",
    type: "word",
    en: "travel insurance",
    kana: "トラベル インシュランス",
    ja: "海外旅行保険",
    pos: "名詞",
    example: "We have travel insurance from Japan.",
    exampleJa: "日本で入った旅行保険があります。",
    note: "受診時に必ず聞かれます。保険証券の番号をスマホに控えておきましょう。",
  },
  {
    id: "vc-trb-08",
    group: "trouble",
    type: "word",
    en: "jet lag",
    kana: "ジェット ラグ",
    ja: "時差ぼけ",
    pos: "名詞",
    example: "I'm still fighting jet lag.",
    exampleJa: "まだ時差ぼけと戦っています。",
  },
  {
    id: "vc-trb-09",
    group: "trouble",
    type: "word",
    en: "food poisoning",
    kana: "フード ポイズニング",
    ja: "食あたり",
    pos: "名詞",
    example: "I think I got food poisoning.",
    exampleJa: "食あたりかもしれません。",
  },
  {
    id: "vc-trb-10",
    group: "trouble",
    type: "idiom",
    en: "get lost",
    kana: "ゲット ロスト",
    ja: "道に迷う",
    pos: "熟語",
    example: "We got lost in the subway station.",
    exampleJa: "駅の中で迷ってしまいました。",
  },
  {
    id: "vc-trb-11",
    group: "trouble",
    type: "idiom",
    en: "look for",
    kana: "ルック フォー",
    ja: "〜を探す",
    pos: "熟語",
    example: "I'm looking for my wife.",
    exampleJa: "妻を探しています。",
  },
  {
    id: "vc-trb-12",
    group: "trouble",
    type: "idiom",
    en: "keep an eye on",
    kana: "キープ アン アイ オン",
    ja: "〜から目を離さない",
    pos: "熟語",
    example: "Keep an eye on your bag.",
    exampleJa: "かばんから目を離さないでください。",
  },
  {
    id: "vc-trb-13",
    group: "trouble",
    type: "idiom",
    en: "run into",
    kana: "ラン イントゥ",
    ja: "(問題などに)ぶつかる・偶然出会う",
    pos: "熟語",
    example: "We ran into a problem with our booking.",
    exampleJa: "予約でひとつ問題が起きました。",
  },
  {
    id: "vc-trb-14",
    group: "trouble",
    type: "idiom",
    en: "call off",
    kana: "コール オフ",
    ja: "中止する",
    pos: "熟語",
    example: "They called off the tour because of the rain.",
    exampleJa: "雨のためツアーは中止になりました。",
  },
];

export const WORD_BY_ID: Record<string, WordEntry> = Object.fromEntries(
  WORDS.map((w) => [w.id, w]),
);

export function wordsOf(group: WordGroup): WordEntry[] {
  return WORDS.filter((w) => w.group === group);
}

export const WORD_TYPE_LABELS: Record<WordType, string> = {
  word: "単語",
  idiom: "熟語",
};
